Create TABLE  person2 (
        FirstName VARCHAR(50) DEFAULT NULL,
        MiddleName VARCHAR(50) DEFAULT NULL,
        LastName VARCHAR(50) DEFAULT NULL,
		Street1 VARCHAR(50) DEFAULT NULL,
		Street2 VARCHAR(50) DEFAULT NULL,
		City VARCHAR(50) DEFAULT NULL,
		StateName VARCHAR(50) DEFAULT NULL,
		Zip VARCHAR(50) DEFAULT NULL,
		Phone VARCHAR(50) DEFAULT NULL,
		Email VARCHAR(50) DEFAULT NULL,
		Cell VARCHAR(50) DEFAULT NULL,
		Instaurl VARCHAR(50) DEFAULT NULL    
)